# Nazwa serwisu, któr? zobaczymy w panelu Eureki
spring.application.name=service-discovery

# Port, na którym b?dzie dzia?a? Eureka. Standard bran?owy to 8761
server.port=8761

# --- Kluczowa Konfiguracja ---
# Te dwie linijki mówi? Eurece: "Jeste? serwerem, nie próbuj
# rejestrowa? SAMEGO SIEBIE u innego serwera Eureka."
# W trybie produkcyjnym (dla klastra) wygl?da?oby to inaczej.
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false